### PR TITLE
Update to 4.11.10

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
```
 SHExpandLSQ.F95:(.text.shexpandlsq_+0xe75): undefined reference to `dggglm_'
  /home/conda/feedstock_root/build_artifacts/pyshtools_1705746686698/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: SHExpandLSQ.F95:(.text.shexpandlsq_+0x1b5c): undefined reference to `dgels_'
 ```

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by MarkWieczorek** [comment]
Thanks for looking into this, even though it's still failing... Do you have any ideas on how to debug this? If there is an internal problem with the new Meson backend, we could perhaps open an issue with them.

**Pull request closed without merging**
