### PR TITLE
pyshtools v4.12.2 with Python 3.12 support

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by jan-janssen** [comment]
@markwieczorek the pull request is ready for review.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by MarkWieczorek** [comment]
This looks great! I'll try to look this over by the end of the day (end of weekend worst case scenario...)

**Comment by MarkWieczorek** [comment]
Thanks a million. I don't think I would have figured this one out!

**Comment by jan-janssen** [comment]
> Thanks a million. I don't think I would have figured this one out!

I am happy to help. I was still a bit surprised that I had to specify the links to the libraries manually, maybe there is something on the `meson` side that could be improved to fix this issue. But I am definitely no expert.

**Pull request merged**
