### PR TITLE
Fix lapack issues

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by MarkWieczorek** [comment]
Hi! Could you let me know why it is desirable not to provide versions dependencies for liblapack and fftw ? For info, I only provided the link to this old issue on twitter because the conda-forge user didn't seem to understand the complexities involved with using numpy with different lapack/blas/mkl backends.

**Comment by moorepants** [comment]
I think it is because certain core packages are all pinned here: https://github.com/conda-forge/conda-forge-pinning-feedstock. FFTW is one of them, for example. This is to ensure a conda forge wide compatibility.

**Comment by moorepants** [comment]
LGTM

**Comment by MarkWieczorek** [comment]
Sorry for the delay....

**Pull request merged**
