### PR TITLE
Add Support for Windows

### PR DESCRIPTION
**Pull request by EricAtORS**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I need the windows version of the package but the conda-forge knowledge base isn't clear on how I can build locally on windows. So I'm opening a PR to see how the build goes.

I took some of the changes fom #20 for the test portion of it. I opened a new PR in order to champion this issue through and getting it merged.

I am not great at conda-forge stuff, so best practices may not be there, but hopefully, it will build correctly and I will look for help from the offical conda-forge resources if it doesn't build.

Thanks for the great work @MarkWieczorek

### CODE REVIEW

**Comment by EricAtORS** [comment]
It builds fine one windows, but for some reason, on python 3.10 on all platforms, it's falling back to numpy built against python 3.6. It's going to be fun to resolve.

**Comment by EricAtORS** [comment]
I'm not sure if the fix to compile on python 3.10 was because I pinned fftw or because I reran conda-smithy on linux instead of windows.

**Comment by EricAtORS** [comment]
@MarkWieczorek,
Is there something I can do to help move the review forward?

**Comment by MarkWieczorek** [comment]
Sorry for delay in getting back to you, but I literally *just* moved between two different cities... I'll try to find time in the next couple days to take a look.

**Comment by MarkWieczorek** [comment]
@moorepants @megies @mreineck Would one of you mind taking a quick look at this PR that adds windows support to pyshtools? All that I can say is that all the builds in the checks above for linux/macos/win seem to work for python 3.8-3.10. I'm willing to accept this as is, but to be honest, I'm not qualified to evaluate the changes!

**Comment by EricAtORS** [comment]
Thanks for the update!
I hope your move went well.

**Comment by MarkWieczorek** [comment]
Don't worry, I haven't forgot. I'll try to take care of this on friday when I should have more free time.

**Comment by mreineck** [comment]
> @moorepants @megies @mreineck Would one of you mind taking a quick look at this PR that adds windows support to pyshtools? 

Sorry for the long silence ... I'm currently on vacation with fairly bad internet access. I can have a look early next week, but I'm certainly no expert on configuring for Windows.

**Comment by MarkWieczorek** [comment]
Ok. I'll wait a week. I'm on vacation too, and the last windows machine I used was in the 80s (have they gotten any better since then?)

**Comment by moorepants** [comment]
I looked over the meta.yaml file. The changes seem fine.

**Comment by EricAtORS** [comment]
Thanks Everyone! Have a great vacation!

**Pull request merged**
