### PR TITLE
Remove openblas from the recipe and add numpy pin.

### PR DESCRIPTION
**Pull request by moorepants**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by moorepants** [comment]
@MarkWieczorek I think this should be merged first and then try your local install. If you still have issues, then we investigate further.

**Comment by MarkWieczorek** [comment]
mkl isn't used in the build, so it is probably ok. I will look everything over in more detail in about 4 hours....

**Comment by moorepants** [comment]
The way it works is that the package is built against the netlib implementations if you only use `libblas` and `liblapack` in the recipe. Then in the tests or when you install the appropriate package openblas (unix) and mkl (win) will be installed instead of the netlib versions. If you want to use different versions locally you can switch the implementation installed in your conda environment. So, hopefully this corrects things.

**Review by MarkWieczorek — APPROVED** [review]
pinning numpy is definitely a good idea. I don't fully understand removing openblas, but it appears that libopenblas gets installed as a dependency. The checks all work, so I am ok with this!

**Comment by moorepants** [comment]
Try the install once it is is pushed to anaconda.org.

**Pull request merged**
