### PR TITLE
Fix ARM OSX migration

### PR DESCRIPTION
**Pull request by k-dominik**
Hello @conda-forge/pyshtools,

I built upon #36 and tried to fix the build for `osx-arm64`. I think I succeeded by

* adding a patch to fix `pkg_resources` import, which I [opened a PR upstream](https://github.com/SHTOOLS/SHTOOLS/pull/375), so that in principle it can be removed for builds after it has been accepted
* added a patch to skip doc building - I'd say skipping building of docs is a good idea in any case for the conda recipe.
  * having said that - I don't know anything about this package - during the tests there will be "errors" complaining that the docs are not there - so it might be required?! 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by k-dominik** [comment]
@conda-forge admin, please restart ci

**Comment by k-dominik** [comment]
@conda-forge-admin please restart ci

**Comment by MarkWieczorek** [comment]
fyi, I just put out a new minor release (4.10.2). I've asked the bot to rerun the migration PR, and we'll see what happens. I suspect that there is still a problem with the docs, but I couldn't find the old logs. In any case, each time I rerun the ARM migration, a different problem arises!

**Comment by MarkWieczorek** [comment]
See comments in https://github.com/conda-forge/pyshtools-feedstock/pull/39

**Comment by MarkWieczorek** [comment]
I'm going to close this because i think that this is now working in the last PR: https://github.com/conda-forge/pyshtools-feedstock/pull/41

In essence, I changed how the documentation was built. The only potential problem I see is that the ARM64 builds aren't running the test suite (this runs on all the other platforms).

**Pull request closed without merging**
