### PR TITLE
Redo osx-arm64 migration with doc building patch.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
I _think_ this will allow the cross build to osx-arm64 to work.  The CI will tell me if I'm right...

**Comment by erykoff** [comment]
Oh blah, that was able to run the correct build (not host) python, but then it couldn't load the library which was built for the host (not build) target.  The options are to either (a) do a complete build in both envs (but I don't know if this will work well) or (b) skip the docs build.  I don't know how essential those are?

**Comment by MarkWieczorek** [comment]
If it is impossible to fix this, then I could try to save all the formatted doc strings as part of the git repo (instead of doing it as part of the build process). I just feel that this would be kind of a hack, but not a horrible one...

**Comment by MarkWieczorek** [comment]
I am going to close this because I think it is all working in the last PR: https://github.com/conda-forge/pyshtools-feedstock/pull/41

The only potential problem we are having is that the ARM64 builds don't run the test suite for some reason (this runs on all the other platforms).

**Pull request closed without merging**
