### PR TITLE
Win32

### PR DESCRIPTION
**Pull request by xoviat**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xoviat** [comment]
@conda-forge-admin rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender.

**Comment by xoviat** [comment]
note: a patch may be necessary to resolve the "module" issue

https://github.com/xoviat/flang/blob/windows/tools/driver/Upper.cpp#L846-L852

**Comment by xoviat** [comment]
fixed in xoviat/flang@30b5411f8226386a642fdee0429101ed153c6604; need rebuild

**Comment by xoviat** [comment]
ref conda-forge/flang-feedstock#20

**Comment by MarkWieczorek** [comment]
It looks like this is the problem:
```
flang.exe:f90: src\FFTW3.f95
  F90-F-0004-Unable to open MODULE file iso_c_binding.mod (src\FFTW3.f95: 7)
```
The `FFTW3.f95` file uses this line:
```
  use, intrinsic :: iso_c_binding
```
I can't remember the details here, but it is my understanding that this is an F2008(?) extension, and that it is implemented by "almost all" fortran compilers. It looks like "flang.exe" doesn't implement this yet.

When we build the windows wheels, I believe that we are using the mingw gfortran compiler: https://github.com/SHTOOLS/build-shtools/blob/master/appveyor.yml . Perhaps we should try to use mingw with the conda build as well???

**Edit:**
`iso_c_binding` is a Fortran 2003 standard.

**Comment by xoviat** [comment]
I am the author of flang for windows and the numpy blas detection. The solution is to fix flang so that it works correctly.  The numpy blas detection failed because lapack was pinned (cb335fc). flang supports `iso_c_binding`, and conda build works correctly when run on my local computer. I will try to display the include path so see what is happening.

**Comment by xoviat** [comment]
GetShortPath is used to convert paths. I wonder if that's the problem...

**Comment by xoviat** [comment]
build fails because the winapi `_access('\bld\PYSHTO~1\_BUILD~1\Library/include/flang/iso_c_binding.mod', 0)` returns -1, when the file is present:

```
 Directory of D:\bld\PYSHTO~1\_BUILD~1\Library\include\flang

02/02/2021  11:00 PM    <DIR>          .
02/02/2021  11:00 PM    <DIR>          ..
01/31/2021  08:10 PM            66,630 ieee_arithmetic.mod
01/31/2021  08:10 PM            66,658 ieee_arithmetic_la.mod
01/31/2021  08:10 PM            35,597 ieee_exceptions.mod
01/31/2021  08:10 PM            35,625 ieee_exceptions_la.mod
01/31/2021  08:10 PM             7,626 ieee_features.mod
01/31/2021  08:10 PM            11,666 iso_c_binding.mod
```

I cannot reproduce this on my local pc, or with conda build. Unclear what the next step is.

**Comment by xoviat** [comment]
see https://github.com/xoviat/flang/commit/7c11324d27349d23feb93309d5710cb28fdda0d8

**Comment by xoviat** [comment]
what's more confusing is that it returned path access before.

**Comment by xoviat** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=272726&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=3cc4a9ed-60e1-5810-6eb3-5f9cd4a26dba&l=495

**Comment by xoviat** [comment]
@moorepants it's ready.

**Comment by moorepants** [comment]
The changes seem to be adding `python setup.py build`, removing the pins on fftw and liblapack, adding blas/cblas explicitly, and disabling the test on windows. It imports on windows, but should there be at least a test to show that the bindings to the lower level codes do work?

**Comment by xoviat** [comment]
Numpy is not working in the test for some reason; not sure why. flang also doesn't seem to work inside pip for some reason.

**Comment by MarkWieczorek** [comment]
Do the tests run on your personal machine? If you could point me to the error I will take a look at it.

**Comment by xoviat** [comment]
The error is here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=274630&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea

```
Traceback (most recent call last):
  File "./ClassExample.py", line 5, in <module>
    import numpy as np
  File "D:\bld\pyshtools_1612650140689\_test_env\lib\site-packages\numpy\__init__.py", line 145, in <module>
    from . import core
  File "D:\bld\pyshtools_1612650140689\_test_env\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
Makefile:63: recipe for target 'ClassInterface/ClassExample.py.phony' failed
ImportError: 
make: Leaving directory '/cygdrive/d/bld/pyshtools_1612650140689/test_tmp/pyshtools-4.8/examples/python'

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
```

not sure what the problem is. I usually can run dependency walker to find the dependencies, but not sure how to do download the files.

**Comment by xoviat** [comment]
@MarkWieczorek is there a way to download the artifacts?

**Comment by xoviat** [comment]
@conda-forge-admin rerender

**Comment by xoviat** [comment]
@MarkWieczorek not sure which DLL is failing to load. Dependency walker shows the following dependencies:

- LIBCBLAS
- PYTHON39
- KERNEL32
- VCRUNTIME140

**Comment by xoviat** [comment]
note: I just noticed that the 3.6 build does pass.

**Comment by MarkWieczorek** [comment]
I'm going to close this given that the windows packages are now building....

**Pull request closed without merging**
